from typing import Optional, Literal, List

from src.core.data.domain.base import DomainObject
from src.core.tools.base import Tool
from src.core.agents.roles.base import Role


class Message(DomainObject):
    content: Optional[str] = None
    """The contents of the message."""

    refusal: Optional[str] = None
    """The refusal message generated by the model."""

    role: Role
    """The role of the author of this message."""

    tool_calls: Optional[List[Tool]] = None
    """The tool calls generated by the model, such as function calls."""
