endpoints:
  - name: gpt-4o-mini_completions
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-4o-mini
      config:
        openai_api_key: $OPENROUTER_API_KEY
        openai_api_base: https://openrouter.ai/api/v1

    limit:
      renewal_period: minute
      calls: 10

  - name: gpt-4o-mini_chat
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-4o-mini
      config:
        openai_api_key: $OPENAI_API_KEY
    limit:
      renewal_period: minute
      calls: 10

  - name: embeddings
    endpoint_type: llm/v1/embeddings
    model:
      provider: openai
      name: text-embedding-ada-002
      config:
        openai_api_key: $OPENAI_API_KEY
    limit:
      renewal_period: minute
      calls: 10

  - name: gemini_flash_latest
    endpoint_type: llm/v1/chat
    model:
      proxy: openrouter
      provider: google
      name: gemini-flash-8b-1.5-exp
      config:
        openai_api_key: $OPENROUTER_API_KEY
        openai_api_base: https://openrouter.ai/api/v1
    limit:
      renewal_period: minute
      calls: 10

  # Small Language Models
  - name: phi-3.5-mini-128k-instruct
    endpoint_type: llm/v1/chat
    model:
      proxy: openrouter
      provider: openai
      name: microsoft/phi-3.5-mini-128k-instruct
      config:
        openai_api_key: $OPENROUTER_API_KEY
        openai_api_base: https://openrouter.ai/api/v1

  - name: best
    endpoint_type: llm/v1/chat
    model:
      proxy: openrouter
      provider: openai
      name: openrouter/auto
      config:
        openai_api_key: $OPENROUTER_API_KEY
        openai_api_base: https://openrouter.ai/api/v1

 - name: vllm_test
    endpoint_type: llm/v1/chat
    model:
      proxy: vllm
      provider: openai
      name: foo/foo
      config:
        openai_api_key: $VLLM_API_KEY
        openai_api_base: $VLLM_API_BASE
